# Generated by Django 4.2.6 on 2024-02-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_cart_remove_product_additional_images_order_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='return_policy',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
