# Generated by Django 4.2.6 on 2024-02-18 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_alter_category_slug_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
